### ISSUE TITLE
omega

### ISSUE THREAD

**Issue by ColtNovak** [om3ga6400/om3ga6400.github.io#2]
@om3ga6400  
I open sourced our app challenge project that never actually got finished if you wanna mess around with it. the codes broken probably though
https://github.com/kumja1/YourFit-Congressional-App-Challenge-2024

**Comment by ColtNovak** [comment]
just make some pull requests

**Comment by om3ga6400** [comment]
> just make some pull requests

we have a chat room in fish why u here

**Comment by ColtNovak** [comment]
idk

**Comment by ColtNovak** [comment]
but I want contributors for this lol

**Comment by om3ga6400** [comment]
I don't know flutter

**Comment by ColtNovak** [comment]
oh alr , neither do we 💀

**Comment by om3ga6400** [comment]
who other person

**Comment by ColtNovak** [comment]
jesse

**Comment by om3ga6400** [comment]
he at our school?

**Comment by ColtNovak** [comment]
yeah

**Comment by ColtNovak** [comment]
nah nrn
